### ISSUE TITLE
`python3 -m varlink.cli` parses address and interface incorrectly

### ISSUE THREAD

**Issue by TomasTomecek** [varlink/python#5]
Using the sample described in readme from this repo:
```
$ python3 -m varlink.tests.test_orgexamplemore --varlink="unix:/tmp/test"
Listening on /tmp/test
```

```
$ python3 -m varlink.cli help unix:/tmp/test/org.example.more
Traceback (most recent call last):
  File "/usr/lib64/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib64/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/tt/g/varlink/python/varlink/cli.py", line 107, in <module>
    args.func(args)
  File "/home/tt/g/varlink/python/varlink/cli.py", line 60, in varlink_help
    client = varlink.Client(address)
  File "/home/tt/g/varlink/python/varlink/client.py", line 328, in __init__
    if address[0] == '@':
IndexError: string index out of range
```

**Comment by haraldh** [comment]
Hmm, works for me.. do you have an old version lying around?

**Comment by TomasTomecek** [comment]
+1
